Feature/cheat 73 utworzyc screen widok postaci
infoshareacademy/jfdzr3-projects-cheater-games pull request #45
Opened 2021-08-03 18:19 UTC by ossowskid

Created Character information panel.
This panel shows:
- Name of character,
- class of character,
- XP gained,
- Stats,
- Image of class

Please veryfi, and merge.

2021-08-05 21:06 UTC, AnnaSawickaZiolkowska reviewed
W surowcach, złoto, drewno, materiały warto dodać padding taki sam jak statystykach.
Linia 204 i 207 do zmiany znacznik <p>, aby usunąć warningi z consoli.
Linia 127 można zmienić color="#00695f" na color="initial". znika warning
Między tekstem zdobyte doświadczenie a CircularProgress warto dodać odstęp.

2021-08-06 14:21 UTC, AnnaSawickaZiolkowska approved these changes

2021-08-06 14:58 UTC, cytrowski requested changes
W konsoli po starcie jest masa warningów - wyczyść je zanim to zmerdżujemy. Mam wrażenie, że domerdżowałeś gałąź Marcina do siebie. Zobaczę, czy da się to naprawić.

2021-08-06 18:40 UTC, cytrowski approved these changes

2021-08-06 18:42 UTC, merged